TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = eglpsl1ght

LIBRARY_INCLUDES = \
	-I$(TOP)/src/gallium/state_trackers/egl \
	-I$(TOP)/src/gallium/state_trackers/vega \
	-I$(TOP)/src/egl/main \
	-I$(TOP)/src/mesa

C_SOURCES = egl_psl1ght.c

include ../../Makefile.template
